---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Install requirements to build obs-studio
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 43200
    name: "{{ obs_build_packages }}"
  when: compile_obs|bool

- apt_repository:
    repo: "deb https://debian.ethz.ch/debian/ stretch stable main contrib non-free"
    state: present
  when: compile_obs|bool

- name: Install nonfree requirements to build obs-studio
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 43200
    name: "{{ packages }}"
  vars:
    packages:
      - libavcodec-dev
      - libavfilter-dev
      - libavdevice-dev
      - libfdk-aac-dev
  when: compile_obs|bool

- name: Install old version of obs-studio
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 43200
    name: "{{ packages }}"
  vars:
    packages:
      - obs-studio
      - ffmpeg
  when: not compile_obs|bool

- name: Create cache directory
  file:
    path: /var/cache/toolbox-obs-studio
    state: directory

- name: Check if obs should be installed
  copy:
    src: files/README.txt
    dest: /var/cache/toolbox-obs-studio/README.txt
  register: obs_installed

- pause:
    prompt: OBS Installation will be skipped. To Change that please delete /var/cache/toolbox-obs-studio/README.txt
    seconds: 23
  when: not obs_installed.changed

- name: clone obs-studio source
  git:
    repo: 'https://github.com/obsproject/obs-studio.git'
    dest: /var/cache/toolbox-obs-studio/git
    clone: yes
    update: yes
    recursive: yes
  when: obs_installed.changed

- name: Create cache directory
  file:
    path: /var/cache/toolbox-obs-studio/git/build
    state: directory
  when: obs_installed.changed

- name: cmake obs-studio
  command:  cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=/usr ..
  args:
    chdir: /var/cache/toolbox-obs-studio/git/build
  when: obs_installed.changed

- name: make obs-studio
  make:
    chdir: /var/cache/toolbox-obs-studio/git/build/
    target: all
    params:
      NUM_THREADS: 4
  when: obs_installed.changed

#- name: checkinstall obs-studio
#  command: checkinstall --pkgname=obs-studio --fstrans=no --backup=no --pkgversion="$(date +%Y%m%d)-git" --deldoc=yes 
#  args:
#    chdir: /var/cache/toolbox-obs-studio/git/build
#  when: obs_installed.changed

- pause:
    prompt: 'Please install obs-studio by habd wit this command: cd /var/cache/toolbox-obs-studio/git/build/; sudo checkinstall --pkgname=obs-studio --fstrans=no --backup=no  --pkgversion="$(date +%Y%m%d)-git" --deldoc=yes '
  when: obs_installed.changed
